version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: scanner_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: scanner_user
      POSTGRES_PASSWORD: scanner_pass
      POSTGRES_DB: scanner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: